sudo: false

language: java

jdk: oraclejdk7

cache:
  directories:
  - $HOME/build/LorenzoBettini/packtpub-xtext-book-examples/director
  - $HOME/build/LorenzoBettini/packtpub-xtext-book-examples/buckminster
  - $HOME/build/LorenzoBettini/packtpub-xtext-book-examples/buildroot

env: DISPLAY=:99.0

install: true

before_script:
 - sh -e /etc/init.d/xvfb start
 
script:
 - export
 - ant -f org.example.releng/build.ant -Dcommands.file=$HOME/build/LorenzoBettini/packtpub-xtext-book-examples/org.example.releng/commands-no-swtbot.txt